[package]
name = "git_utils_shared"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"
description = "Reusable git helpers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
tabled = "0.7.0"
chrono = "0.4.19"
